DATA:
  benchmark: 'chuac'
  datapath: /coronary_dataset/CHUAC/
  classes: 1
  architecture: 'EAG_SAE_ESTF'

  backbone: 'base'
  in_ch: 1
  steps: 3
  use_fim: [True, True, True, True]
  up: [True, True, True, True]
  affinity: [[3,9,15], 3, 3, 3]
  affinity_supervised: [True, False, False, False]
  reduce_dim: False

TRAIN:
  logname:/coronary_dataset/CHUAC  #save log and model
  train_gpu: [0]
  start_epoch: 0
  epochs: 500  
  img_mode: crop 
  img_size: 256
  test_size: 512
  nworker: 8
  batch_size: 2  
  batch_size_val: 1
  evaluate: True
  resume: False 
  optimizer: 'adam'
  base_lr:  0.0001
  lr_update: True
  lr_step: 250  
  ignore_label: 255
  weight_decay: 0.0005
  gamma: 0.9
  momentum: 0.9
  weight: /coronary_dataset/CHUAC.log/
  trans: True
